# Generated by Django 6.0.5 on 2026-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_allocation_reserved_until'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='provider',
            field=models.CharField(choices=[('sumup', 'SumUp')], default='sumup', max_length=32),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider', 'provider_payment_id'], name='payments_pa_provide_e030c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider', 'provider_payment_id'), name='unique_provider_payment_id'),
        ),
    ]
