# Generated by Django 6.0.5 on 2026-09-04 14:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventorybatch_closed_at_inventorybatch_closed_by_and_more'),
        ('products', '0003_producttranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('business', 'Business'), ('retail', 'Retail')], max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('short_dated', 'Short dated'), ('damaged_package', 'Damaged package'), ('promotion', 'Promotion'), ('other', 'Other')], max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_prices', to='inventory.inventorybatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_prices', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PriceAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('SEK', 'Swedish krona')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='pricing.commercialprice')),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
        migrations.AddIndex(
            model_name='commercialprice',
            index=models.Index(fields=['channel', 'enabled'], name='pricing_com_channel_900222_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprice',
            index=models.Index(fields=['product', 'channel'], name='pricing_com_product_60677f_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprice',
            index=models.Index(fields=['batch', 'channel'], name='pricing_com_batch_i_f10093_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercialprice',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True)), fields=('product', 'channel'), name='unique_product_price_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='commercialprice',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False)), fields=('batch', 'channel'), name='unique_batch_price_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='priceamount',
            constraint=models.UniqueConstraint(fields=('commercial_price', 'currency'), name='unique_price_amount_per_currency'),
        ),
        migrations.AddConstraint(
            model_name='priceamount',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', Decimal('0.00'))), name='price_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='priceamount',
            constraint=models.CheckConstraint(condition=models.Q(('original_price__isnull', True), ('original_price__gt', Decimal('0.00')), _connector='OR'), name='original_price_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='priceamount',
            constraint=models.CheckConstraint(condition=models.Q(('original_price__isnull', True), ('original_price__gte', models.F('price')), _connector='OR'), name='original_price_not_below_price'),
        ),
    ]
