# Generated by Django 6.0.5 on 2026-06-04 12:27

import accounts.roles
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[(accounts.roles.StaffAccessLevel['RESTRICTED'], 'Restricted'), (accounts.roles.StaffAccessLevel['FULL'], 'Full')], default=accounts.roles.StaffAccessLevel['RESTRICTED'], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_customer_membership_per_user'), models.UniqueConstraint(fields=('user', 'customer'), name='unique_customer_membership')],
            },
        ),
    ]
