# Generated by Django 6.0.5 on 2026-06-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0002_customer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermembership',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='customers.customer'),
        ),
    ]
