# Generated by Django 6.0.5 on 2026-06-06 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customermembership_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customermembership',
            name='unique_customer_membership_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='customermembership',
            name='unique_customer_membership',
        ),
        migrations.AlterField(
            model_name='customermembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
