# Generated by Django 6.0.5 on 2026-05-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('boxes', models.PositiveIntegerField()),
                ('best_before', models.DateField()),
                ('location', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('depleted', 'Depleted'), ('closed', 'Closed')], default='active', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='products.product')),
            ],
            options={
                'ordering': ['best_before', 'batch_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('boxes__gte', 0)), name='inventorybatch_boxes_gte_0')],
            },
        ),
    ]
