# Generated by Django 6.0.5 on 2026-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=120)),
                ('address_line', models.CharField(max_length=180)),
            ],
            options={
                'ordering': ['name', 'email'],
            },
        ),
    ]
