"""
Product application services.

public API:
    create_product(...)
        -> Create product or return existing product with same SKU/internal number.

    update_product(...)
        -> Update editable product catalog fields and profile data.

    update_product_active(...)
        -> Compatibility wrapper for status-only updates.
"""

from __future__ import annotations

from django.db import IntegrityError, transaction

from common.results import ServiceResult
from products.catalog import (
    make_sku,
    normalize_optional_text,
    normalize_required_text,
    validate_internal_number,
    validate_weight_per_unit,
)
from products.errors import InvalidProductData
from products.models import Product, ProductProfile


@transaction.atomic
def create_product(
    *,
    brand: str,
    name: str,
    weight_per_unit: int,
    stock_unit: str = Product.StockUnit.BOX,
    internal_number: int | None = None,
    manufacturer: str = "",
    vegan: bool = False,
) -> ServiceResult[Product]:
    """Create product or return existing product.

    SKU is generated by the Product model on create. If internal_number is
    provided, the SKU will be SS-001 style. Otherwise it falls back to a
    brand/name/weight based SKU.
    """

    normalized_brand = normalize_required_text(brand, field_name="brand")
    normalized_name = normalize_required_text(name, field_name="name")
    normalized_manufacturer = normalize_optional_text(
        manufacturer,
        field_name="manufacturer",
    )

    validate_weight_per_unit(weight_per_unit)
    validate_internal_number(internal_number)
    _validate_stock_unit(stock_unit)

    sku = make_sku(
        internal_number=internal_number,
        brand=normalized_brand,
        name=normalized_name,
        weight_per_unit=weight_per_unit,
    )

    existing = Product.objects.filter(sku=sku).first()
    if existing is not None:
        return ServiceResult(
            item=existing,
            message="Product already exists in the catalog.",
            created=False,
        )

    if internal_number is not None:
        existing = Product.objects.filter(
            internal_number=internal_number,
        ).first()

        if existing is not None:
            return ServiceResult(
                item=existing,
                message="Product already exists in the catalog.",
                created=False,
            )

    try:
        product = Product.objects.create(
            internal_number=internal_number,
            manufacturer=normalized_manufacturer,
            brand=normalized_brand,
            name=normalized_name,
            weight_per_unit=weight_per_unit,
            stock_unit=stock_unit,
            vegan=vegan,
        )
    except IntegrityError as exc:
        existing = Product.objects.filter(sku=sku).first()
        if existing is not None:
            return ServiceResult(
                item=existing,
                message="Product already exists in the catalog.",
                created=False,
            )

        raise InvalidProductData(f"Could not create product with SKU {sku}") from exc

    ProductProfile.objects.get_or_create(product=product)

    return ServiceResult(
        item=product,
        message="Product added to the catalog.",
        created=True,
    )


@transaction.atomic
def update_product(
    *,
    product: Product,
    internal_number: int | None,
    manufacturer: str,
    brand: str,
    name: str,
    active: bool,
    vegan: bool,
    description: str = "",
    ingredients: str = "",
    image_url: str = "",
) -> Product:
    """Update editable product catalog data.

    SKU, weight_per_unit and stock_unit are intentionally not editable here.
    """

    product = (
        Product.objects
        .select_for_update()
        .get(pk=product.pk)
    )

    validate_internal_number(internal_number)

    if internal_number is not None:
        number_is_taken = (
            Product.objects
            .filter(internal_number=internal_number)
            .exclude(pk=product.pk)
            .exists()
        )

        if number_is_taken:
            raise InvalidProductData(
                f"Product number {internal_number} already exists"
            )

    product.internal_number = internal_number
    product.manufacturer = manufacturer
    product.brand = brand
    product.name = name
    product.active = active
    product.vegan = vegan

    try:
        product.save(
            update_fields=[
                "internal_number",
                "manufacturer",
                "brand",
                "name",
                "active",
                "vegan",
            ]
        )
    except IntegrityError as exc:
        raise InvalidProductData("Could not update product") from exc

    profile, _created = ProductProfile.objects.select_for_update().get_or_create(
        product=product,
    )

    profile.description = description.strip()
    profile.ingredients = ingredients.strip()
    profile.image_url = image_url.strip()
    profile.save(
        update_fields=[
            "description",
            "ingredients",
            "image_url",
        ]
    )

    return product


@transaction.atomic
def update_product_active(
    *,
    product: Product,
    active: bool,
) -> Product:
    """Update mutable catalog status.

    Kept as a small compatibility wrapper because views/tests may still call it.
    """

    product = Product.objects.select_for_update().get(pk=product.pk)
    product.active = active
    product.save(update_fields=["active"])

    return product


def _validate_stock_unit(stock_unit: str) -> None:
    valid_units = {choice.value for choice in Product.StockUnit}

    if stock_unit not in valid_units:
        raise InvalidProductData(f"Unsupported stock unit: {stock_unit}")
