# Generated by Django 6.0.5 on 2026-09-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_remove_orderline_unique_product_per_order'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOfferSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_order_line_selections', to='pricing.commercialprice')),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_offer_selection', to='orders.orderline')),
            ],
        ),
    ]
