# Generated by Django 6.0.5 on 2026-09-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_remove_orderline_unique_product_per_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickChecklistMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pick_checklist_mark', to='orders.allocation')),
            ],
            options={
                'verbose_name': 'Pick checklist mark',
                'verbose_name_plural': 'Pick checklist marks',
            },
        ),
    ]
