# Generated by Django 6.0.5 on 2026-08-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailPostalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country_code', 'postal_code', 'city'],
                'indexes': [models.Index(fields=['country_code', 'postal_code'], name='retail_reta_country_86df47_idx'), models.Index(fields=['enabled'], name='retail_reta_enabled_cadafb_idx')],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'postal_code', 'city'), name='unique_retail_postal_area')],
            },
        ),
    ]
