# Generated by Django 6.0.5 on 2026-08-26 13:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producttranslation'),
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=32)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=120)),
                ('address_line', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='retail.retailorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_order_lines', to='products.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='retail_order_line_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price_snapshot__gt', Decimal('0.00'))), name='retail_order_line_unit_price_positive'), models.CheckConstraint(condition=models.Q(('line_total__gte', Decimal('0.00'))), name='retail_order_line_total_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='RetailPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='retail_price', to='products.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='retail_price_amount_positive')],
            },
        ),
    ]
