# Generated by Django 6.0.5 on 2026-08-26 13:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorybatch_closed_at_inventorybatch_closed_by_and_more'),
        ('retail', '0002_retailorder_retailorderline_retailprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailBatchOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retail_offer', to='inventory.inventorybatch')),
            ],
            options={
                'indexes': [models.Index(fields=['enabled'], name='retail_reta_enabled_4ac241_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gt', Decimal('0.00')), _connector='OR'), name='retail_batch_offer_price_positive_or_null'), models.CheckConstraint(condition=models.Q(('enabled', False), ('price__isnull', False), _connector='OR'), name='retail_batch_offer_enabled_requires_price')],
            },
        ),
    ]
