# Generated by Django 6.0.5 on 2026-08-26 14:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producttranslation'),
        ('retail', '0003_retailbatchoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='retailprice',
            name='retail_price_amount_positive',
        ),
        migrations.AddField(
            model_name='retailproductoffer',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='retail_offer', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='retailprice',
            name='product',
        ),
        migrations.AddIndex(
            model_name='retailproductoffer',
            index=models.Index(fields=['enabled'], name='retail_reta_enabled_2559e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='retailproductoffer',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gt', Decimal('0.00')), _connector='OR'), name='retail_product_offer_price_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='retailproductoffer',
            constraint=models.CheckConstraint(condition=models.Q(('enabled', False), ('price__isnull', False), _connector='OR'), name='retail_product_offer_enabled_requires_price'),
        ),
        migrations.DeleteModel(
            name='RetailPrice',
        ),
    ]
