# Generated by Django 6.0.5 on 2026-08-28 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_currency_orderline_unit_price_snapshot_and_more'),
        ('retail', '0004_retailproductoffer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retail_checkout', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='retail_reta_expires_56d9b0_idx')],
            },
        ),
    ]
