# Generated by Django 6.0.5 on 2026-08-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_allocation_reserved_until'),
        ('retail', '0005_retailcheckoutsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailOfferSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_line_selections', to='retail.retailbatchoffer')),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retail_offer_selection', to='orders.orderline')),
                ('product_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_line_selections', to='retail.retailproductoffer')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('batch_offer__isnull', True), ('product_offer__isnull', False)), models.Q(('batch_offer__isnull', False), ('product_offer__isnull', True)), _connector='OR'), name='retail_offer_selection_exactly_one_offer')],
            },
        ),
    ]
