# Generated by Django 6.0.5 on 2026-09-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0006_retailofferselection'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retailorderline',
            name='retail_order_line_quantity_positive',
        ),
        migrations.RemoveConstraint(
            model_name='retailorderline',
            name='retail_order_line_unit_price_positive',
        ),
        migrations.RemoveConstraint(
            model_name='retailorderline',
            name='retail_order_line_total_non_negative',
        ),
        migrations.RemoveField(
            model_name='retailorderline',
            name='order',
        ),
        migrations.RemoveField(
            model_name='retailorderline',
            name='product',
        ),
        migrations.DeleteModel(
            name='RetailOrder',
        ),
        migrations.DeleteModel(
            name='RetailOrderLine',
        ),
    ]
