# Generated by Django 6.0.5 on 2026-09-04 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_remove_retailorderline_retail_order_line_quantity_positive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailCartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_lines', to='retail.retailbatchoffer')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='retail.retailcart')),
                ('product_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_lines', to='retail.retailproductoffer')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('batch_offer__isnull', True), ('product_offer__isnull', False)), models.Q(('batch_offer__isnull', False), ('product_offer__isnull', True)), _connector='OR'), name='retail_cart_line_exactly_one_offer'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='retail_cart_line_quantity_positive'), models.UniqueConstraint(condition=models.Q(('product_offer__isnull', False)), fields=('cart', 'product_offer'), name='unique_retail_product_offer_per_cart'), models.UniqueConstraint(condition=models.Q(('batch_offer__isnull', False)), fields=('cart', 'batch_offer'), name='unique_retail_batch_offer_per_cart')],
            },
        ),
    ]
