# Generated by Django 6.0.5 on 2026-09-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('retail', '0008_retailcart_retailcartline'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='retailbatchoffer',
            name='retail_reta_enabled_4ac241_idx',
        ),
        migrations.RemoveConstraint(
            model_name='retailbatchoffer',
            name='retail_batch_offer_price_positive_or_null',
        ),
        migrations.RemoveConstraint(
            model_name='retailbatchoffer',
            name='retail_batch_offer_enabled_requires_price',
        ),
        migrations.RemoveIndex(
            model_name='retailproductoffer',
            name='retail_reta_enabled_2559e7_idx',
        ),
        migrations.RemoveConstraint(
            model_name='retailproductoffer',
            name='retail_product_offer_price_positive_or_null',
        ),
        migrations.RemoveConstraint(
            model_name='retailproductoffer',
            name='retail_product_offer_enabled_requires_price',
        ),
        migrations.RemoveConstraint(
            model_name='retailcartline',
            name='retail_cart_line_exactly_one_offer',
        ),
        migrations.RemoveConstraint(
            model_name='retailcartline',
            name='unique_retail_product_offer_per_cart',
        ),
        migrations.RemoveConstraint(
            model_name='retailcartline',
            name='unique_retail_batch_offer_per_cart',
        ),
        migrations.RemoveConstraint(
            model_name='retailofferselection',
            name='retail_offer_selection_exactly_one_offer',
        ),
        migrations.AddField(
            model_name='retailcartline',
            name='commercial_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_cart_lines', to='pricing.commercialprice'),
        ),
        migrations.AddField(
            model_name='retailofferselection',
            name='commercial_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_order_line_selections', to='pricing.commercialprice'),
        ),
        migrations.AddConstraint(
            model_name='retailcartline',
            constraint=models.UniqueConstraint(condition=models.Q(('commercial_price__isnull', False)), fields=('cart', 'commercial_price'), name='unique_retail_commercial_price_per_cart'),
        ),
        migrations.RemoveField(
            model_name='retailproductoffer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='retailcartline',
            name='batch_offer',
        ),
        migrations.RemoveField(
            model_name='retailcartline',
            name='product_offer',
        ),
        migrations.RemoveField(
            model_name='retailofferselection',
            name='batch_offer',
        ),
        migrations.RemoveField(
            model_name='retailofferselection',
            name='product_offer',
        ),
        migrations.DeleteModel(
            name='RetailBatchOffer',
        ),
        migrations.DeleteModel(
            name='RetailProductOffer',
        ),
    ]
