# Generated by Django 6.0.5 on 2026-09-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('retail', '0009_remove_retailbatchoffer_retail_reta_enabled_4ac241_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retailcartline',
            name='unique_retail_commercial_price_per_cart',
        ),
        migrations.AlterField(
            model_name='retailcartline',
            name='commercial_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_cart_lines', to='pricing.commercialprice'),
        ),
        migrations.AlterField(
            model_name='retailofferselection',
            name='commercial_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_order_line_selections', to='pricing.commercialprice'),
        ),
        migrations.AddConstraint(
            model_name='retailcartline',
            constraint=models.UniqueConstraint(fields=('cart', 'commercial_price'), name='unique_retail_commercial_price_per_cart'),
        ),
    ]
