# Generated by Django 6.0.5 on 2026-05-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('packed', 'Packed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, choices=[('customer_request', 'Customer request'), ('order_entry_error', 'Order entry error'), ('duplicate_order', 'Duplicate order'), ('out_of_stock', 'Out of stock'), ('other', 'Other')], max_length=40)),
                ('cancel_note', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_cancelled', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_delivered', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_edited', to=settings.AUTH_USER_MODEL)),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_packed', to=settings.AUTH_USER_MODEL)),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_placed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('boxes', 'Boxes'), ('kg', 'Kg'), ('grams', 'Grams')], max_length=20)),
                ('quantity_in_boxes', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('consumed', 'Consumed'), ('cancelled', 'Cancelled')], default='reserved', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.inventorybatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orders.order')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orders.orderline')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='orders_orde_custome_c9b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['edited_at'], name='orders_orde_edited__a8ebbc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['placed_at'], name='orders_orde_placed__076a37_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['packed_at'], name='orders_orde_packed__393392_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivered_at'], name='orders_orde_deliver_1355ff_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cancelled_at'], name='orders_orde_cancell_248ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order'], name='orders_orde_order_i_44a8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['product'], name='orders_orde_product_4f6bf3_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_product_per_order'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orderline_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_in_boxes__gt', 0)), name='orderline_quantity_in_boxes_gt_0'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['status'], name='orders_allo_status_89c1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['order', 'status'], name='orders_allo_order_i_d66c46_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['batch', 'status'], name='orders_allo_batch_i_32cc21_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('boxes__gt', 0)), name='allocation_boxes_gt_0'),
        ),
    ]
