# Generated by Django 6.0.5 on 2026-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address_line_snapshot',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_city_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_country_snapshot',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
