# Generated by Django 6.0.5 on 2026-06-16 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_activated_at_customer_activated_by_and_more'),
        ('orders', '0002_order_customer_address_line_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('customer',), name='unique_draft_order_per_customer'),
        ),
    ]
