# Generated by Django 6.0.5 on 2026-08-28 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_activated_at_customer_activated_by_and_more'),
        ('orders', '0003_order_unique_draft_order_per_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_draft_order_per_customer',
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('business', 'Business'), ('retail', 'Retail')], default='business', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'business'), ('status', 'draft')), fields=('customer',), name='unique_business_draft_order_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('channel', 'retail'), ('customer__isnull', False), _connector='OR'), name='business_order_requires_customer'),
        ),
    ]
