# Generated by Django 6.0.5 on 2026-08-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_unique_draft_order_per_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_address_line_snapshot',
            new_name='buyer_address_line_snapshot',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_city_snapshot',
            new_name='buyer_city_snapshot',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_country_snapshot',
            new_name='buyer_country_snapshot',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_email_snapshot',
            new_name='buyer_email_snapshot',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name_snapshot',
            new_name='buyer_name_snapshot',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_phone_snapshot',
            new_name='buyer_phone_snapshot',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_postal_code_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
