# Generated by Django 6.0.5 on 2026-08-28 13:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_customer_address_line_snapshot_order_buyer_address_line_snapshot_and_more'),
        ('products', '0003_producttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='orderline',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_snapshot__isnull', True), ('unit_price_snapshot__gt', Decimal('0.00')), _connector='OR'), name='orderline_unit_price_positive_or_null'),
        ),
    ]
