# Generated by Django 6.0.5 on 2026-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_currency_orderline_unit_price_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
