# Generated by Django 6.0.5 on 2026-09-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_allocation_reserved_until'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderline',
            name='unique_product_per_order',
        ),
    ]
