# Generated by Django 6.0.8 on 2026-09-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_backfill_order_line_commercial_offer'),
        ('pricing', '0002_create_business_standard_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='commercial_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='pricing.commercialprice'),
        ),
    ]
