# Generated by Django 6.0.5 on 2026-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('weight_per_box', models.PositiveIntegerField()),
                ('sku', models.CharField(editable=False, max_length=160, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['brand', 'name', 'weight_per_box'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'name', 'weight_per_box'), name='unique_product_brand_name_weight')],
            },
        ),
    ]
