# Generated by Django 6.0.5 on 2026-05-29 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.PositiveSmallIntegerField(blank=True, help_text='Informal internal product number used with customers.', null=True, unique=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer or producer, e.g. Fazer, Cloetta, BUBS.', max_length=160)),
                ('brand', models.CharField(help_text='Brand or product line.', max_length=160)),
                ('name', models.CharField(help_text='Swedish/internal MVP product name.', max_length=160)),
                ('weight_per_unit', models.PositiveIntegerField(help_text='Weight in grams for one physical stock unit.')),
                ('stock_unit', models.CharField(choices=[('box', 'Box'), ('piece', 'Piece'), ('bag', 'Bag'), ('case', 'Case')], default='box', help_text='Physical inventory unit used for this product.', max_length=20)),
                ('sku', models.CharField(editable=False, max_length=180, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('vegan', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['internal_number', 'brand', 'name', 'weight_per_unit'],
                'constraints': [models.CheckConstraint(condition=models.Q(('internal_number__isnull', True), ('internal_number__gte', 1), _connector='OR'), name='product_internal_number_positive_or_null'), models.CheckConstraint(condition=models.Q(('weight_per_unit__gte', 1)), name='product_weight_per_unit_at_least_min'), models.CheckConstraint(condition=models.Q(('weight_per_unit__lte', 50000)), name='product_weight_per_unit_at_most_max')],
            },
        ),
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='External image URL. Prefer this over uploads for MVP/Railway.', max_length=500)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='products.product')),
            ],
            options={
                'ordering': ['product__brand', 'product__name'],
            },
        ),
    ]
