# Generated by Django 6.0.5 on 2026-05-24 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='External image URL. Prefer this over uploads for MVP/Railway.', max_length=500)),
            ],
            options={
                'ordering': ['product__brand', 'product__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['internal_number', 'brand', 'name', 'weight_per_box']},
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_brand_name_weight',
        ),
        migrations.AddField(
            model_name='product',
            name='internal_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Informal internal product number used with customers.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer or producer, e.g. Fazer, Cloetta, BUBS.', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(help_text='Brand or product line.', max_length=160),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Swedish/internal MVP product name.', max_length=160),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(editable=False, max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_per_box',
            field=models.PositiveIntegerField(help_text='Stored in grams.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('internal_number__isnull', True), ('internal_number__gte', 1), _connector='OR'), name='product_internal_number_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('weight_per_box__gte', 1)), name='product_weight_per_box_at_least_min'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('weight_per_box__lte', 50000)), name='product_weight_per_box_at_most_max'),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='products.product'),
        ),
    ]
