# Generated by Django 6.0.5 on 2026-06-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_activated_at_product_activated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('fr', 'French')], help_text='Language shown to customers.', max_length=10)),
                ('name', models.CharField(help_text='Full product name shown to customers in this language. Example: Tutti Frutti Acidulé.', max_length=160, verbose_name='Customer-facing name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'ordering': ['product__brand', 'product__name', 'language_code'],
                'constraints': [models.UniqueConstraint(fields=('product', 'language_code'), name='unique_product_translation_per_language')],
            },
        ),
    ]
