# Generated by Django 6.0.5 on 2026-09-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('candy', 'Candy'), ('chips', 'Chips'), ('dip_mix', 'Dip mix')], default='', help_text='Primary customer catalog category.', max_length=20),
        ),
    ]
