# Generated by Django 6.0.5 on 2026-09-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('candy', 'Candy'), ('chips', 'Chips'), ('dip_mix', 'Dip mix'), ('merchandise', 'Merchandise')], default='', help_text='Primary customer catalog category.', max_length=20),
        ),
    ]
