# Generated by Django 6.0.5 on 2026-09-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productprofile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprofile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='products/originals/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, max_length=255, upload_to='products/thumbnails/%Y/%m/%d/'),
        ),
    ]
